# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yy28NDyyOsUDzO6vBePVMi4OqqGLYRyt
"""

import requests
from bs4 import BeautifulSoup
import csv

headers = {'User-Agent': 'Pixel'}

def generate_prompt(filename):

    session = requests.Session()

    with open(f"{filename}", "r", encoding="utf-8") as in_file:
        data = in_file.readlines()

        with open("out.csv", "w", newline='', encoding="utf-8-sig") as outfile:
          csv_writer = csv.writer(outfile)
          for url in data:
              page = requests.get(url.strip(), headers=headers)
              if page.status_code == 200:
                  query = "Напиши контент для моей веб страницы"
                  page_type = "Тип страниц: категория товаров алкогольной продукции"
                  content_format = "Целевая аудитория: b2b, оптовые заказчики. Тип контента: коммерческий, продающий."
                  text_size = f"Объем контента {1500}"
                  soup = BeautifulSoup(page.text, "html.parser")
                  title = f"Title: {soup.title.string}"
                  description = f"Description: {soup.find('meta', attrs={'name': 'description'}).get('content')}"
                  h1 = f"H1: {soup.h1.string}"

                  csv_writer.writerow([
                      f"{url.strip()}|{query} {page_type} {content_format} {text_size} {title} {description} {h1}"
                  ])

    session.close()

generate_prompt("data.txt")